### ISSUE TITLE
Add some info when hovering over planets

### ISSUE THREAD

**Issue by IRampagingRhin0** [andrewfullard/PyGCEditor#54]
At a minimum faction owner, colours can be hard to distinguish so some text to help people

So it'd be Kuat (Empire)

**Comment by Slornie** [comment]
_Nearly_ got this to work - in a hacky way! 

![image](https://github.com/andrewfullard/PyGCEditor/assets/9806586/489981e1-4e46-4710-9c49-0072ec10ef32)
