### ISSUE TITLE
Change planet placement crash

### ISSUE THREAD

**Issue by IRampagingRhin0** [andrewfullard/PyGCEditor#75]
If you adjust a planets co-ordinates and then try to save it'll crash

<img width="910" alt="image" src="https://github.com/andrewfullard/PyGCEditor/assets/65861702/e1798664-44b0-4101-ad2d-d0e55033c155">

**Comment by andrewfullard** [comment]
It's a custom function that is probably being incorrectly referenced in that `try` block

**Comment by Slornie** [comment]
Oh, right. I see now. I thought xmlTools was a public library!
