### ISSUE TITLE
Traderoute preview issue

### ISSUE THREAD

**Issue by IRampagingRhin0** [andrewfullard/PyGCEditor#86]
Can still make them, but no lines appear
<img width="851" alt="image" src="https://github.com/andrewfullard/PyGCEditor/assets/65861702/0ca0362d-e228-48ce-ae1c-1a874e8a85ec">

**Comment by andrewfullard** [comment]
Presumably added by the changes from Slornie recently?

**Comment by andrewfullard** [comment]
@Slornie

**Comment by Slornie** [comment]
I think @IRampagingRhin0 has worked it out.  Looks like I was overcomplicating things!
